default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432

development:
 <<: *default
 host: <%= ENV["DATABASE_HOST"] %>
 database: <%= ENV["DATABASE_NAME"] %>
 username: <%= ENV["DATABASE_USERNAME"] %>
 password: <%= ENV["DATABASE_PASSWORD"] %>
